apiVersion: v1
kind: Service
metadata:
  name: {{ include "manufacturing-co.fullname" . }}-backend
  labels:
    {{- include "manufacturing-co.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "manufacturing-co.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "manufacturing-co.fullname" . }}-backend-pvc
  labels:
    {{- include "manufacturing-co.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "manufacturing-co.fullname" . }}-backend-secret
  labels:
    {{- include "manufacturing-co.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | quote }}
